name: 'actions-kubeflow'
description: Build, deploy and run a kubeflow pipeline
author: Niklas Hansson
inputs:
  kubeflow_url:
    description: The endpoint where your Kubeflow UI is running. 
    required: true
  workflow_yaml_path:
    description: The full path name including the filename of the YAML file that describes the workflow you want to run on Argo.  This should be relative to the root of the GitHub repository where the Action is triggered.
    require: true
  client_id:
    description: The IAP client id, which was specified when the kubeflow deployment where setup using IAP.
    require: true
outputs:
  WORKFLOW_URL:
    description: URL that is a link to pipeline in Kubeflow
branding:
  color: 'purple'
  icon: 'upload-cloud'
runs:
  using: 'docker'
  image: 'Dockerfile'