name: Compile, Deploy and Run versioned pipeline on Kubeflow
on: [push]

# Set environmental variables
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout files in repo
      uses: actions/checkout@master

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}

    - run: |
        gcloud auth configure-docker
       
    - name: Build preprocessing image
      env: 
        IMAGE_NAME: pre_image
      run: |
        docker build -t gcr.io/$GKE_PROJECT/$IMAGE_NAME:$GITHUB_SHA \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" forecast_peython_wiki/preprocess/.

      - name: Publish preprocessing image
      env: 
        IMAGE: -pre_image-forecasting
      run: |
        echo gcr.io/$GKE_PROJECT/$IMAGE_NAME:$GITHUB_SHA
        docker push gcr.io/$GKE_PROJECT/$IMAGE_NAME:$GITHUB_SHA
  

    - name: Build train forecast image
      env: 
        IMAGE_NAME: train_forecast_image
      run: |
        docker build -t gcr.io/$GKE_PROJECT/$IMAGE_NAME:$GITHUB_SHA \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" forecast_peython_wiki/preprocess/.
    

      - name: Publish train forecast image
      env: 
        IMAGE: train_forecast_image
      run: |
        echo gcr.io/$GKE_PROJECT/$IMAGE_NAME:$GITHUB_SHA
        docker push gcr.io/$GKE_PROJECT/$IMAGE_NAME:$GITHUB_SHA

            
    - name: Submit Kubeflow pipeline
      id: kubeflow
      uses: NikeNano/kubeflow-github-action@versioned_pipeline
      with:
        KUBEFLOW_URL: ${{ secrets.KUBEFLOW_URL }}
        ENCODED_GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GKE_KEY }}
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcloud-sa.json
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        PIPELINE_CODE_PATH: "forecast_peython_wiki/deployment/pipline.py"
        PIPELINE_FUNCTION_NAME: "pipeline"
        PIPELINE_PARAMETERS_PATH: "forecast_peython_wiki/parameters.yaml"
        EXPERIMENT_NAME: "Default"
        RUN_PIPELINE: true
        VERSION_GITHUB_SHA: true
